# Identifiants uniques du projet
sonar.projectKey=product-api-backend
sonar.projectName=Gestion de Produits API
sonar.projectVersion=1.0

# Emplacement du code source (backend uniquement pour l'analyse Python)
sonar.sources=backend
sonar.exclusions=backend/tests/**, frontend/**

# Emplacement des tests pour l'analyse de qualité
sonar.tests=backend/tests
sonar.test.inclusions=backend/tests/**

# Encodage du texte
sonar.sourceEncoding=UTF-8

# Configuration spécifique pour Python
sonar.language=py
sonar.python.version=3.10

# Intégration des rapports de tests et de couverture
# Ces chemins correspondent à ce que le Jenkinsfile génère
sonar.python.xunit.reportPath=nosetests.xml
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.bandit.reportPaths=bandit.out
